import { defineField, defineType } from 'sanity';

export const leadSubmission = defineType({
  name: 'leadSubmission',
  title: 'Lead Submission',
  type: 'document',
  fields: [
    defineField({
      name: 'submittedAt',
      title: 'Submitted At',
      type: 'datetime',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'submissionType',
      title: 'Submission Type',
      type: 'string',
      options: {
        list: [
          { title: 'Contact', value: 'contact' },
          { title: 'General Consultation', value: 'consultation' },
          { title: 'Advanced Skin Imaging & Analysis', value: 'skinAnalysis' },
          { title: 'Suite Rental Application', value: 'suiteRental' },
        ],
      },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      initialValue: 'new',
      options: {
        list: [
          { title: 'New', value: 'new' },
          { title: 'Contacted', value: 'contacted' },
          { title: 'Qualified', value: 'qualified' },
          { title: 'Consultation Booked', value: 'consultationBooked' },
          { title: 'Completed Booking', value: 'completed' },
          { title: 'Booked (Legacy)', value: 'booked' },
          { title: 'Closed', value: 'closed' },
        ],
      },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      validation: (R) => R.required().email(),
    }),
    defineField({
      name: 'phone',
      title: 'Phone',
      type: 'string',
    }),
    defineField({
      name: 'message',
      title: 'Message',
      type: 'text',
      rows: 5,
    }),
    defineField({
      name: 'serviceInterest',
      title: 'Service Interest',
      type: 'string',
      description: 'The consultation, service family, or operational request selected on the form.',
    }),
    defineField({
      name: 'owner',
      title: 'Lead Owner',
      type: 'string',
      description: 'Team member responsible for the next action.',
    }),
    defineField({ name: 'followUpDueAt', title: 'Follow-Up Due', type: 'datetime' }),
    defineField({ name: 'firstContactedAt', title: 'First Contacted', type: 'datetime' }),
    defineField({ name: 'qualifiedAt', title: 'Qualified At', type: 'datetime' }),
    defineField({ name: 'bookedAt', title: 'Consultation Booked At', type: 'datetime' }),
    defineField({ name: 'completedAt', title: 'Completed Booking At', type: 'datetime' }),
    defineField({
      name: 'bookingNotes',
      title: 'Booking Reconciliation Notes',
      type: 'text',
      rows: 3,
      description: 'Record the matching GlossGenius appointment or the reason the lead was closed. Do not paste sensitive clinical details.',
    }),
    defineField({
      name: 'smsConsent',
      title: 'SMS Consent',
      type: 'object',
      readOnly: true,
      description: 'Immutable evidence captured from the public contact form.',
      fields: [
        defineField({
          name: 'informational',
          title: 'Informational',
          type: 'boolean',
          initialValue: false,
          readOnly: true,
        }),
        defineField({
          name: 'marketing',
          title: 'Marketing',
          type: 'boolean',
          initialValue: false,
          readOnly: true,
        }),
        defineField({
          name: 'declined',
          title: 'Declined SMS',
          type: 'boolean',
          initialValue: false,
          readOnly: true,
        }),
        defineField({ name: 'recordedAt', title: 'Recorded At', type: 'datetime', readOnly: true }),
        defineField({ name: 'disclosureVersion', title: 'Disclosure Version', type: 'string', readOnly: true }),
        defineField({ name: 'method', title: 'Consent Method', type: 'string', readOnly: true }),
        defineField({ name: 'termsUrl', title: 'Terms URL', type: 'url', readOnly: true }),
      ],
    }),
    defineField({
      name: 'suiteRental',
      title: 'Suite Rental Details',
      type: 'object',
      fields: [
        defineField({ name: 'specialty', title: 'Specialty', type: 'string' }),
        defineField({ name: 'licenseNumber', title: 'License / Certification #', type: 'string' }),
        defineField({ name: 'businessName', title: 'Business Name', type: 'string' }),
        defineField({ name: 'yearsExperience', title: 'Years of Experience', type: 'string' }),
        defineField({
          name: 'insuranceAcknowledgement',
          title: 'Insurance Acknowledged',
          type: 'boolean',
          initialValue: false,
        }),
      ],
    }),
    defineField({
      name: 'source',
      title: 'Source',
      type: 'object',
      fields: [
        defineField({ name: 'formName', title: 'Form Name', type: 'string' }),
        defineField({ name: 'page', title: 'Page', type: 'string' }),
        defineField({ name: 'userAgent', title: 'User Agent', type: 'string' }),
      ],
    }),
    defineField({
      name: 'attribution',
      title: 'Attribution',
      type: 'object',
      fields: [
        defineField({ name: 'landingPage', title: 'Landing Page', type: 'string' }),
        defineField({ name: 'referrer', title: 'Referrer', type: 'string' }),
        defineField({ name: 'utmSource', title: 'UTM Source', type: 'string' }),
        defineField({ name: 'utmMedium', title: 'UTM Medium', type: 'string' }),
        defineField({ name: 'utmCampaign', title: 'UTM Campaign', type: 'string' }),
        defineField({ name: 'utmTerm', title: 'UTM Term', type: 'string' }),
        defineField({ name: 'utmContent', title: 'UTM Content', type: 'string' }),
        defineField({ name: 'gclid', title: 'Google Click ID', type: 'string', readOnly: true }),
        defineField({ name: 'gbraid', title: 'Google GBRAID', type: 'string', readOnly: true }),
        defineField({ name: 'wbraid', title: 'Google WBRAID', type: 'string', readOnly: true }),
        defineField({
          name: 'openAIAds',
          title: 'OpenAI Ads Attribution',
          type: 'object',
          readOnly: true,
          hidden: true,
          fields: [
            defineField({ name: 'oppref', title: 'OpenAI Ad Reference', type: 'string' }),
            defineField({ name: 'obref', title: 'OpenAI Browser Reference', type: 'string' }),
          ],
        }),
        defineField({
          name: 'consentSnapshot',
          title: 'Measurement Consent Snapshot',
          type: 'object',
          readOnly: true,
          fields: [
            defineField({ name: 'schemaVersion', title: 'Schema Version', type: 'number' }),
            defineField({ name: 'policyVersion', title: 'Policy Version', type: 'string' }),
            defineField({ name: 'analyticsStorage', title: 'Analytics Storage', type: 'string' }),
            defineField({ name: 'adStorage', title: 'Ad Storage', type: 'string' }),
            defineField({ name: 'adUserData', title: 'Ad User Data', type: 'string' }),
            defineField({ name: 'adPersonalization', title: 'Ad Personalization', type: 'string' }),
            defineField({ name: 'recordedAt', title: 'Recorded At', type: 'datetime' }),
          ],
        }),
      ],
    }),
    defineField({ name: 'measurementReceiptHash', title: 'Measurement Receipt Hash', type: 'string', readOnly: true, hidden: true }),
    defineField({ name: 'measurementReceiptExpiresAt', title: 'Measurement Receipt Expires', type: 'datetime', readOnly: true, hidden: true }),
    defineField({ name: 'measurementReceiptUsedAt', title: 'Measurement Receipt Used', type: 'datetime', readOnly: true }),
    defineField({ name: 'measurementEventId', title: 'Measurement Event ID', type: 'string', readOnly: true }),
    defineField({
      name: 'offlineConversions',
      title: 'Google Offline Conversion State',
      type: 'object',
      readOnly: true,
      fields: [
        defineField({ name: 'qualifiedUploadedAt', title: 'Qualified Uploaded', type: 'datetime' }),
        defineField({ name: 'consultationBookedUploadedAt', title: 'Consultation Booked Uploaded', type: 'datetime' }),
        defineField({ name: 'completedBookingUploadedAt', title: 'Completed Booking Uploaded', type: 'datetime' }),
        defineField({
          name: 'attempts',
          title: 'Upload Attempts',
          type: 'array',
          of: [
            {
              type: 'object',
              fields: [
                defineField({ name: 'at', title: 'At', type: 'datetime' }),
                defineField({ name: 'goal', title: 'Goal', type: 'string' }),
                defineField({ name: 'outcome', title: 'Outcome', type: 'string' }),
                defineField({ name: 'requestId', title: 'Google Request ID', type: 'string' }),
                defineField({ name: 'detail', title: 'Detail', type: 'string' }),
              ],
            },
          ],
        }),
        defineField({ name: 'lastError', title: 'Last Upload Error', type: 'text' }),
      ],
    }),
    defineField({ name: 'internalNotificationSent', title: 'Internal Notification Sent', type: 'boolean', readOnly: true }),
    defineField({ name: 'acknowledgementSent', title: 'Client Acknowledgement Sent', type: 'boolean', readOnly: true }),
  ],
  orderings: [
    {
      title: 'Newest First',
      name: 'submittedAtDesc',
      by: [{ field: 'submittedAt', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'email',
      submittedAt: 'submittedAt',
      submissionType: 'submissionType',
    },
    prepare({ title, subtitle, submittedAt, submissionType }) {
      const submitted = submittedAt ? new Date(submittedAt).toLocaleString() : 'No date';
      return {
        title,
        subtitle: `${submissionType ?? 'lead'} - ${subtitle ?? 'no email'} - ${submitted}`,
      };
    },
  },
});
