import { defineField, defineType } from 'sanity';

import {
  isPublicProviderDigitalCardPath,
  isPublicProviderStaticProfileImagePath,
  PUBLIC_PROVIDER_DIGITAL_CARDS,
  PUBLIC_PROVIDER_STATIC_PROFILE_IMAGES,
} from '../../web/src/lib/publicProviderContent';
import { validatePublicCopy } from './validation/publicCopy';

type ProviderVisibilityFields = {
  showOnWebsite?: boolean;
};

type ProviderPublicProfileFields = ProviderVisibilityFields & {
  roleCredential?: string;
  publicRole?: string;
  summary?: string;
  biography?: unknown[];
  serviceFocus?: unknown[];
};

type ProviderSlugValue = {
  current?: string;
};

export function validateProviderDigitalCardPath(value: string | undefined): true | string {
  return !value || isPublicProviderDigitalCardPath(value)
    ? true
    : 'Choose a tap-to-share card route that is currently generated by the website.';
}

export function validateProviderProfileImagePath(value: string | undefined): true | string {
  return !value || isPublicProviderStaticProfileImagePath(value)
    ? true
    : 'Choose an existing generated provider profile image or upload a Sanity profile image.';
}

export function validateProviderPublicProfile(
  value: boolean | undefined,
  context: { document?: unknown },
): true | string {
  if (value !== true) return true;

  const document = context.document as ProviderPublicProfileFields | undefined;
  const hasText = (candidate: string | undefined) => Boolean(candidate?.trim());
  const hasTextItems = (candidate: unknown[] | undefined) =>
    candidate?.some((item) => typeof item === 'string' && item.trim().length > 0) === true;

  if (!hasText(document?.publicRole) && !hasText(document?.roleCredential)) {
    return 'A public provider profile requires a verified public role or role credential.';
  }
  if (!hasText(document?.summary)) {
    return 'A public provider profile requires a directory summary.';
  }
  if (!hasTextItems(document?.biography)) {
    return 'A public provider profile requires at least one biography paragraph.';
  }
  if (!hasTextItems(document?.serviceFocus)) {
    return 'A public provider profile requires at least one current service focus.';
  }

  return true;
}

/**
 * Provider — mirrors the Notion "HOUSE OF ROSE: Providers" database.
 * Chain: Provider → Service → Package/Series.
 */
export const provider = defineType({
  name: 'provider',
  title: 'Provider',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Provider',
      type: 'string',
      description: 'Studio label and public-name fallback. Use the verified name; include the licence type wherever a healthcare practitioner is named.',
      validation: (R) => R.required().custom(validatePublicCopy),
    }),
    defineField({
      name: 'slug',
      title: 'Public Profile Slug',
      type: 'slug',
      options: { source: 'fullName', maxLength: 80 },
      description: 'Used at /about/providers/[slug]/.',
      validation: (R) =>
        R.custom((value: ProviderSlugValue | undefined, context) => {
          const document = context.document as ProviderVisibilityFields | undefined;
          return document?.showOnWebsite === true && !value?.current?.trim()
            ? 'A public provider profile requires a slug.'
            : true;
        }),
    }),
    defineField({
      name: 'fullName',
      title: 'Full Name',
      type: 'string',
      description: 'Verified full name and public-name fallback. Include the licence type wherever a healthcare practitioner is named.',
      validation: (R) => R.custom(validatePublicCopy),
    }),
    defineField({
      name: 'lane',
      title: 'Lane',
      type: 'string',
      options: {
        list: [
          { title: 'Advanced Aesthetics', value: 'advanced-aesthetics' },
          { title: 'Injectables & Medical', value: 'injectables-medical' },
          { title: 'Wellness', value: 'wellness' },
          { title: 'Classic Facials', value: 'classic-facials' },
          { title: 'Beauty & Enhancements', value: 'beauty-enhancements' },
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'roleCredential',
      title: 'Role / Credential',
      type: 'string',
      description: 'Verified role or credential. This becomes the public-role fallback when Public Role is empty.',
      validation: (R) => R.custom(validatePublicCopy),
    }),
    defineField({
      name: 'scopeOfPractice',
      title: 'Scope of Practice',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'productionStatus',
      title: 'Production Status',
      type: 'string',
      options: {
        list: [
          { title: 'In Production', value: 'in-production' },
          { title: 'Room Rental — Own Pricing', value: 'room-rental' },
          { title: 'Parked', value: 'parked' },
        ],
        layout: 'radio',
      },
      initialValue: 'in-production',
    }),
    defineField({
      name: 'showOnWebsite',
      title: 'Show on Website',
      type: 'boolean',
      initialValue: false,
      description: 'Publishes this provider in the About directory and creates a public profile route.',
      validation: (R) => R.custom(validateProviderPublicProfile),
    }),
    defineField({
      name: 'listingOrder',
      title: 'Listing Order',
      type: 'number',
      initialValue: 100,
    }),
    defineField({
      name: 'publicName',
      title: 'Public Name + Credential',
      type: 'string',
      description: 'Include the applicable license type beside a healthcare practitioner’s name, e.g. Diana Morrison, RN.',
      validation: (R) => R.custom(validatePublicCopy),
    }),
    defineField({
      name: 'publicRole',
      title: 'Public Role',
      type: 'string',
      description: 'Use only verified roles and credentials. Do not turn an internal provider lane into a public title.',
      validation: (R) => R.custom(validatePublicCopy),
    }),
    defineField({
      name: 'summary',
      title: 'Directory Summary',
      type: 'text',
      rows: 4,
      description: 'Give enough verified context for a client to understand who this person is and what they currently provide. Avoid a generic benefit line or consultation/process boilerplate.',
      validation: (R) => R.custom(validatePublicCopy),
    }),
    defineField({
      name: 'biography',
      title: 'Website Biography',
      type: 'array',
      description: 'Use natural paragraphs for verified experience, current work, and concrete practice context. Depth is welcome; do not force a fixed paragraph count or repeat a process or candidacy template.',
      of: [{ type: 'text', rows: 5, validation: (R) => R.custom(validatePublicCopy) }],
      validation: (R) => R.max(8),
    }),
    defineField({
      name: 'serviceFocus',
      title: 'Public Service Focus',
      type: 'array',
      of: [{ type: 'string', validation: (R) => R.custom(validatePublicCopy) }],
      description: 'Verified current public service labels only. Do not describe internal provider lanes or add promotional claims.',
    }),
    defineField({
      name: 'profileImage',
      title: 'Profile Image',
      type: 'image',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string', validation: (R) => R.custom(validatePublicCopy) })],
    }),
    defineField({
      name: 'profileImagePath',
      title: 'Static Profile Image Path',
      type: 'string',
      description: 'Optional existing generated web asset. Prefer a Sanity profile image for new providers.',
      options: {
        list: PUBLIC_PROVIDER_STATIC_PROFILE_IMAGES.map(({ title, path }) => ({ title, value: path })),
      },
      validation: (R) => R.custom(validateProviderProfileImagePath),
    }),
    defineField({
      name: 'digitalCardPath',
      title: 'Digital Card Path',
      type: 'string',
      description: 'Optional link to a tap-to-share card route currently generated by the website.',
      options: {
        list: PUBLIC_PROVIDER_DIGITAL_CARDS.map(({ title, path }) => ({ title, value: path })),
      },
      validation: (R) => R.custom(validateProviderDigitalCardPath),
    }),
    defineField({
      name: 'medicallyDirected',
      title: 'Show Medical Director Attribution',
      type: 'boolean',
      initialValue: false,
      description: 'Enable when the public profile describes medically directed services.',
    }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo' }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'roleCredential' },
  },
});
