allowBuilds:
  '@netlify/content-engine': false
  contentful: false
  es5-ext: false
  'esbuild@0.25.12 || 0.28.2': true
  'fsevents@2.3.3': true
  lmdb: false
  msgpackr-extract: false
  'sharp@0.34.5': true
