allowBuilds:
  '@netlify/content-engine': set this to true or false
  contentful: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
